// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ============================================
// SUPABASE CLIENT CONFIGURATION
// ============================================
// CRITICAL: This client connects to your cloud database
// - All user data (coins, sales, profiles) is stored here
// - Data persists independently of app deployments
// - Database is hosted on Supabase, not in your app
//
// Production Deployment:
// - Ensure environment variables are set in Vercel
// - Data will NOT be lost during redeployments
// - Database remains intact across all deployments
// ============================================

// Read from environment variables instead of hardcoding tokens
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env.local file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
